POST http://localhost:5000/api/podcast
content-type: application/json

{
    "authorId": "6260c69b3a0ed95093b7db10",
    "description": "This is a podcast about a paper that is about some science thing",
    "DOI": "10.1111/dome.12082",
    "publishedDate": "22/03/2019",
    "tags": ["TestTag1", "TestTag2", "TestTag4"],
    "category": "Engineering",
    "Title": "Some generic Title1 that explains what this is about"
} 

###

PUT http://localhost:5000/api/user/6260c69b3a0ed95093b7db10
content-type: application/json

{
"firstName":"smokey",
"lastName":"thebear",
"email":"forest@fire.com",
"title":"Bear",
"organization":"The woods"
}

###

GET http://localhost:5000/api/podcasts

###


POST http://localhost:5000/api/login 
content-type: application/json

{
    "email": "test@email.com",
    "password": "PlainTextPassword"
}

###

GET http://localhost:5000/api/podcasts/author/62621ea11a5b974b6ceea450 

###

GET http://localhost:5000/api/podcast/byId/6261ff8ca2c510e7645a0611


###

PUT http://localhost:5000/api/podcast/6261ff8ca2c510e7645a0611
content-type: application/json

{
"title":"Some generic Title that explains what this is about",
"journal":"Science Journal",
"publishedDate":"2022-04-20",
"DOI":"10.1111/dome.12082",
"tags":"TestTag1,TestTag2,TestTag4"
}

###

GET http://localhost:5000/api/user/62621ea11a5b974b6ceea450