POST http://localhost:3000/podcast
content-type: application/json

{
    "authorId": "62603f51779a89548e6cc0ec",
    "description": "This is a podcast about a paper that is about some science thing",
    "DOI": "10.1111/dome.12082",
    "publishedDate": "22/03/2019",
    "tags": ["TestTag1", "TestTag2", "TestTag3"],
    "category": "Healthcare"
} 

###

POST http://localhost:3000/user 
content-type: application/json

{
    "firstName":"John",
    "lastName":"Doe",
    "email":"test@email.com",
    "password":"PlainTextPassword"
}

###

GET http://localhost:3000/podcasts/author/62603f51779a89548e6cc0ec/category/Computer-Science

###



