POST http://localhost:5000/podcast
content-type: application/json

{
    "authorId": "62603f51779a89548e6cc0ec",
    "description": "This is a podcast about a paper that is about some science thing",
    "DOI": "10.1111/dome.12082",
    "publishedDate": "22/03/2019",
    "tags": ["TestTag1", "TestTag2", "TestTag3"],
    "category": "Healthcare"
} 

###

PUT http://localhost:5000/api/user/62603f51779a89548e6cc0ec
content-type: application/json

{
"firstName":"Joseph",
"lastName":"Stalin",
"email":"dictator@email.com",
"title":"aa",
"organization":"aa"
}

###

GET http://localhost:5000/podcasts/author/62603f51779a89548e6cc0ec/category/Computer-Science

###


POST http://localhost:5000/api/login 
content-type: application/json

{
    "email": "test@email.com",
    "password": "PlainTextPassword"
}